---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  namespace: sock-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: sock-shop
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: socks-ingress
  namespace: sock-shop
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: sock-shop.davyjones.me
    http:
      paths:
      - path: /
        backend:
          serviceName: front-end
          servicePort: 80
  tls:
  - hosts:
    - sock-shop.davyjones.me
    secretName: front-end-crt-secret
